/**
 * The guided tour's neighbourhood and designs.
 *
 *   npm run tour:build
 *
 * Writes two GENERATED files from committed data only (no network):
 *
 *   public/tour/mankato.thermal-network.json   a project file: downtown
 *       Mankato from the OSM and federal-structure fixtures, the 2018 zone
 *       weather the calibration uses, and the place names. The tour opens it
 *       through `openProject`, as a player's own file would open.
 *   src/education/generated/tourDesigns.ts     the designs the steps name:
 *       the suggestion as the tool would make it here, and three changes to
 *       it. Computed here, once, so each step's claim can be tested against
 *       the design it shows (tests/tour.test.ts).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { calibrationWeather } from '../calibrate/weatherFixture.ts';
import { suggestDesign } from '../../src/engine/design.ts';
import type { Design } from '../../src/engine/design.ts';
import { runScenario } from '../../src/engine/scenario.ts';
import { projectJson } from '../../src/io/project.ts';
import { siteForCounty } from '../../src/relay/relay.ts';
import type { WeatherPayload } from '../../src/relay/relay.ts';
import { boreholeRoom, classifySite } from '../../src/site/classify.ts';
import { centroid } from '../../src/site/geometry.ts';
import { EMPTY_SELECTION, toNeighbourhood } from '../../src/site/neighbourhood.ts';
import type { SiteData } from '../../src/site/osm.ts';
import type { Structures } from '../../src/site/structures.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const read = <T>(p: string) => JSON.parse(readFileSync(resolve(root, p), 'utf8')) as T;

const osm = read<{ data: SiteData }>('tests/fixtures/sites/mankato-downtown.json').data;
const { structures } = read<{ structures: Structures }>('tests/fixtures/structures/mankato-downtown.json');
const buildings: SiteData = { ...osm, structures };
const place = { ...siteForCounty('27013')!, town: 'Mankato', state: 'MN' };
const w = calibrationWeather(place.zone);
const weather: WeatherPayload = {
  year: 2018,
  timezone: 'America/Chicago',
  temperature: Array.from(w.temperature),
  relativeHumidity: Array.from(w.relativeHumidity ?? []),
  ghi: Array.from(w.ghi),
  firstWeekday: w.firstWeekday,
  attribution: `NLR AMY2018 weather, ${w.place}`,
};

// The suggestion exactly as the Design tab would make it for this site.
const site = classifySite(buildings);
const neighbourhood = toNeighbourhood(site, EMPTY_SELECTION, place.zone, place.region);
const asIs = runScenario(neighbourhood, { sources: [] }, w);
const suggestion = suggestDesign({
  peakHeatingW: asIs.site.peakHeatingW,
  peakCoolingW: asIs.site.peakCoolingW,
  sources: site.sources,
  centre: centroid(site.boundary),
  boreholeRoom: boreholeRoom(site.openSpaceM2),
});
const river = (d: Design, capacityW: number): Design => ({ ...d, sources: d.sources.map((s) => (s.kind === 'water' ? { ...s, capacityW } : s)) });
const floor = (d: Design, min: number): Design => ({ ...d, band: { min, max: d.band.max } });

const designs = {
  /** Nothing built: business as usual and the site's own numbers. */
  none: { sources: [], band: suggestion.band, retrofit: 1 } satisfies Design,
  suggestion,
  /** The loop allowed down to −1 °C. */
  colder: floor(suggestion, -1),
  /** And the river exchanger at 8 MW. */
  river: floor(river(suggestion, 8e6), -1),
  /** And a deep envelope retrofit, the floor at −3 °C. */
  final: { ...floor(river(suggestion, 8e6), -3), retrofit: 0.6 },
};

writeFileSync(
  resolve(root, 'public/tour/mankato.thermal-network.json'),
  projectJson({
    saved: '2026-09-28T00:00:00.000Z',
    boundary: osm.boundary,
    selection: EMPTY_SELECTION,
    design: designs.none,
    challenge: null,
    placeEdits: { neighbourhood: 'Downtown', town: 'Mankato', state: 'MN' },
    units: 'ip',
    snapshot: { place, buildings, weather },
  }),
);

writeFileSync(
  resolve(root, 'src/education/generated/tourDesigns.ts'),
  `/**
 * GENERATED by \`npm run tour:build\` — do not edit. The designs the guided
 * tour's steps name, computed for downtown Mankato
 * (public/tour/mankato.thermal-network.json).
 */
import type { Design } from '../../engine/design';

export type TourDesignId = ${Object.keys(designs).map((k) => `'${k}'`).join(' | ')};

export const TOUR_FILE = '/tour/mankato.thermal-network.json';

export const TOUR_DESIGNS: Readonly<Record<TourDesignId, Design>> = ${JSON.stringify(designs, null, 1)};
`,
);
console.log(`tour: ${site.buildings.length} buildings; designs ${Object.keys(designs).join(', ')}`);
