/**
 * County → climate zone, from NLR's spatial tract lookup.
 *
 *   npm run geo:counties
 *
 * The same table ComStock 2025 R3 used to place its buildings, so a county
 * lands in the zone its calibration was fitted in. Streams the 28 MB CSV and
 * keeps one row per county. A county that spans two zones in the tract table
 * (none should — zones are drawn on county lines) fails the run rather than
 * picking one quietly.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { streamCsv } from '../calibrate/csv.mjs';

const URL =
  'https://oedi-data-lake.s3.amazonaws.com/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2025/comstock_amy2018_release_3/geographic_information/spatial_tract_lookup_table_publish_v10.csv';

/** NHGIS county GISJOIN (G SS 0 CCC 0) → 5-digit FIPS. */
const fipsOf = (gisjoin) => `${gisjoin.slice(1, 3)}${gisjoin.slice(4, 7)}`;

async function main() {
  const zones = {};
  const names = {};
  let header = null;
  let rows = 0;
  await streamCsv(URL, (row) => {
    if (!header) {
      header = Object.fromEntries(row.map((name, i) => [name, i]));
      for (const col of ['nhgis_county_gisjoin', 'climate_zone_ashrae_2006', 'resstock_county_id']) {
        if (header[col] === undefined) throw new Error(`Missing column ${col}`);
      }
      return;
    }
    if (row.length < 5) return;
    rows++;
    const fips = fipsOf(row[header.nhgis_county_gisjoin]);
    const zone = row[header.climate_zone_ashrae_2006];
    if (zones[fips] && zones[fips] !== zone) {
      throw new Error(`County ${fips} has tracts in ${zones[fips]} and ${zone}`);
    }
    zones[fips] = zone;
    names[fips] = row[header.resstock_county_id];
  });

  const sorted = Object.keys(zones).sort();
  const byZone = {};
  for (const f of sorted) byZone[zones[f]] = (byZone[zones[f]] ?? 0) + 1;
  console.log(`${rows} tracts → ${sorted.length} counties`, byZone);

  const out = `/**
 * GENERATED by scripts/geo/counties.mjs — do not edit.
 * ASHRAE 169-2006 climate zone by county (5-digit FIPS), from NLR's spatial
 * tract lookup (ComStock 2025 R3 geographic_information), so a county lands
 * in the zone its load calibration was fitted in.
 */
export const COUNTY_ZONE: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(sorted.map((f) => [f, zones[f]])))};

/** "ST, County Name" for display. */
export const COUNTY_NAME: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(sorted.map((f) => [f, names[f]])))};
`;
  writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../../src/engine/generated/counties.ts'), out);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
