/**
 * Grid carbon: NLR Cambium 2023 long-run marginal emission rates.
 *
 *   npm run carbon:extract
 *
 * Downloads the public LRMER workbook (17 MB, data.nlr.gov submission 230),
 * levelizes it exactly as the workbook's own "Levelized LRMER" tab does at its
 * defaults, and writes `src/engine/generated/cambium.ts`: one CO₂ rate per GEA
 * region × month × hour, and the county → region map the map phase will use
 * to place a neighbourhood on the grid.
 *
 * Why LRMER: it is NLR's metric for a long-lived change in electricity demand
 * — the change a thermal network is — counting how the grid's build-out
 * responds, not just which plant is on the margin today. The workbook's
 * guidance says as much.
 *
 * The levelization, from the workbook's Lookups tab: every year from the start
 * year through start + period − 1 is weighted by 1/(1+r)^(y − start), and each
 * year's rate is interpolated linearly between the 5-year values published.
 * Defaults, kept: CO₂, combustion only, start 2025, 20 years, 3% real,
 * Mid-case, end-use (no distribution-loss adjustment).
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LEVELIZATION, levelizationWeights, MIDCASE_CO2_COMBUSTION } from './levelize.mjs';
import { openWorkbook } from './xlsx.mjs';

const URL = 'https://data.nlr.gov/system/files/230/1707947178-Cambium23_LRMER_GEAregions_0.xlsx';
const CITATION =
  'Gagnon, Pieter. 2024. Long-run Marginal Emission Rates for Electricity - Workbooks for 2023 Cambium Data. NREL Data Catalog, submission 230.';

async function download() {
  const cache = join(tmpdir(), 'Cambium23_LRMER_GEAregions.xlsx');
  if (existsSync(cache)) return cache;
  const response = await fetch(URL);
  if (!response.ok) throw new Error(`${response.status} fetching ${URL}`);
  writeFileSync(cache, Buffer.from(await response.arrayBuffer()));
  return cache;
}

const canonicalRegion = (name) => String(name).trim().replace(/ /g, '_');

async function main() {
  const book = openWorkbook(await download());
  const weights = levelizationWeights();

  const rows = book.sheet('Data - Month-hour');
  const regions = [];
  const rates = {}; // region → 12 × 24, g/kWh (= kg/MWh)
  let region = null;
  for (let r = 5; r < rows.length; r++) {
    const row = rows[r];
    if (!row) continue;
    if (row[1]) {
      region = canonicalRegion(row[1]);
      if (!rates[region]) {
        regions.push(region);
        rates[region] = Array.from({ length: 12 }, () => new Array(24).fill(null));
      }
    }
    const month = row[2] ?? null;
    const hour = row[3];
    if (region === null || typeof hour !== 'number') continue;
    // The month is written only on hour 0 of each month; carry it.
    if (typeof month === 'number') rates[region].currentMonth = month;
    const m = rates[region].currentMonth;
    const values = MIDCASE_CO2_COMBUSTION.map((c) => row[c]);
    if (values.some((v) => typeof v !== 'number')) throw new Error(`${region} ${m}/${hour}: missing data`);
    rates[region][m - 1][hour] = Number(values.reduce((s, v, k) => s + v * weights[k], 0).toFixed(1));
  }

  for (const r of regions) {
    delete rates[r].currentMonth;
    const missing = rates[r].flat().filter((v) => v === null).length;
    if (missing) throw new Error(`${r}: ${missing} month-hours missing`);
  }
  if (regions.length !== 18) throw new Error(`Expected 18 GEA regions, found ${regions.length}`);

  // County → region, keyed by the 5-digit FIPS code.
  const counties = {};
  const countyRows = book.sheet('County Mapping');
  for (let r = 1; r < countyRows.length; r++) {
    const row = countyRows[r];
    if (!row || typeof row[0] !== 'number' || typeof row[1] !== 'number') continue;
    const fips = `${String(row[0]).padStart(2, '0')}${String(row[1]).padStart(3, '0')}`;
    const index = regions.indexOf(canonicalRegion(row[6]));
    if (index < 0) throw new Error(`County ${fips} maps to unknown region ${row[6]}`);
    counties[fips] = index;
  }

  const annualMean = Object.fromEntries(
    regions.map((r) => [r, Number((rates[r].flat().reduce((a, b) => a + b, 0) / 288).toFixed(1))]),
  );
  console.log(`${regions.length} regions, ${Object.keys(counties).length} counties. Flat-mean g/kWh:`);
  console.log(annualMean);

  const out = `/**
 * GENERATED by scripts/carbon/extract.mjs — do not edit.
 *
 * ${CITATION}
 * Cambium 2023 long-run marginal CO₂ emission rates (combustion), ${LEVELIZATION.scenario},
 * levelized ${LEVELIZATION.startYear}–${LEVELIZATION.startYear + LEVELIZATION.years - 1} at ${LEVELIZATION.discountRate * 100}% real, end-use.
 * g CO₂ per kWh, by GEA region × month (0 = January) × hour of day in the
 * region's local standard time.
 */

export const GEA_REGIONS = ${JSON.stringify(regions)} as const;

export type GeaRegion = (typeof GEA_REGIONS)[number];

export const LRMER_G_PER_KWH: Readonly<Record<GeaRegion, readonly (readonly number[])[]>> = ${JSON.stringify(rates)};

/** 5-digit county FIPS → index into GEA_REGIONS. */
export const COUNTY_REGION: Readonly<Record<string, number>> = ${JSON.stringify(counties)};
`;
  const path = resolve(dirname(fileURLToPath(import.meta.url)), '../../src/engine/generated/cambium.ts');
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, out);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
